export default {
  AuthNavigator: 'AuthNavigator',
  TabNavigator: 'TabNavigator',
  TravelNavigator: 'TravelNavigator',
  FlightsNavigator: 'FlightsNavigator',
  ChartbotNavigator: 'ChartbotNavigator',
  HotelsNavigator: 'HotelsNavigator',
  ProfileNavigator: 'ProfileNavigator',
  AuthLoadingView: 'AuthLoadingView',
  WelcomeView: 'WelcomeView',
  LoginView: 'LoginView',
  SignUpView: 'SignUpView',
  ForgotPasswordView: 'ForgotPasswordView',
  TravelFeedView: 'TravelFeedView',
  FlightsFeedView: 'FlightsFeedView',
  ChartbotView: 'ChartbotView',
  HotelsFeedView: 'HotelsFeedView',
  ProfileView: 'ProfileView',
  FindFlightView: 'FindFlightView',
  FindHotelView: 'FindHotelView'
}
