export default {
  AuthNavigator: 'AuthNavigator',
  TabNavigator: 'TabNavigator',
  TravelNavigator: 'TravelNavigator',
  FlightsNavigator: 'FlightsNavigator',
  ChatbotNavigator: 'ChatbotNavigator',
  HotelsNavigator: 'HotelsNavigator',
  ProfileNavigator: 'ProfileNavigator',
  AuthLoadingView: 'AuthLoadingView',
  WelcomeView: 'WelcomeView',
  LoginView: 'LoginView',
  SignUpView: 'SignUpView',
  ForgotPasswordView: 'ForgotPasswordView',
  TravelFeedView: 'TravelFeedView',
  FlightsFeedView: 'FlightsFeedView',
  ChatbotView: 'ChatbotView',
  HotelsFeedView: 'HotelsFeedView',
  ProfileView: 'ProfileView',
  FindFlightView: 'FindFlightView',
  BookHotelView: 'BookHotelView',
  HotelDetailsView: 'HotelDetailsView'
};
